/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "FreeRTOS.h"
#include "task.h"
#include <stdint.h>

/* ---------------- SYSTEM CORE CLOCK ---------------- */
uint32_t SystemCoreClock = 72000000UL;

/* ---------------- STM32F3 REGISTERS ---------------- */
#define RCC_AHBENR   (*(volatile uint32_t*)0x40021014)

#define GPIOE_MODER  (*(volatile uint32_t*)0x48001000)
#define GPIOE_ODR    (*(volatile uint32_t*)0x48001014)

/* ---------------- LED PIN ---------------- */
#define LED_PIN 8   // PE8

/* ---------------- FreeRTOS HOOKS ---------------- */
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    (void)xTask;
    (void)pcTaskName;

    __asm volatile ("cpsid i");
    while (1)
    {
        GPIOE_ODR ^= (1 << LED_PIN);
    }
}

void vApplicationMallocFailedHook(void)
{
    __asm volatile ("cpsid i");
    while (1)
    {
        GPIOE_ODR ^= (1 << LED_PIN);
    }
}

/* ---------------- GPIO INIT ---------------- */
void GPIO_Init(void)
{
    /* Enable GPIOE clock */
    RCC_AHBENR |= (1 << 21);

    /* Configure PE8 as output (01) */
    GPIOE_MODER &= ~(3 << (LED_PIN * 2));
    GPIOE_MODER |=  (1 << (LED_PIN * 2));
}

/* ---------------- LED TASK ---------------- */
void LED_Task(void *pvParameters)
{
    (void)pvParameters;

    while (1)
    {
        GPIOE_ODR ^= (1 << LED_PIN);
        vTaskDelay(pdMS_TO_TICKS(500));
    }
}

/* ---------------- MAIN ---------------- */
int main(void)
{
    GPIO_Init();

    /* Create task (IMPORTANT: 256 words minimum) */
    if (xTaskCreate(LED_Task, "LED", 256, NULL, 1, NULL) != pdPASS)
    {
        while (1)
        {
            GPIOE_ODR ^= (1 << LED_PIN);
        }
    }

    /* Start scheduler */
    vTaskStartScheduler();

    /* Should never reach here */
    while (1)
    {
        GPIOE_ODR ^= (1 << LED_PIN);
    }
}


