/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


// Write a code to interface a switch connected to PA0 and control an LED at PE8 such that the LED turns ON when the switch is pressed and turns OFF when released.

#include <stdint.h>

#define RCC_Base		0x40021000
#define RCC_AHBENR		(*(volatile uint32_t*)(RCC_Base + 0x14))

#define GPIOE_Base		0x48001000
#define GPIOE_MODER		(*(volatile uint32_t*)(GPIOE_Base + 0x00))
#define GPIOE_ODR		(*(volatile uint32_t*)(GPIOE_Base + 0x14))

#define GPIOA_Base		0x48000000
#define GPIOA_MODER		 (*(volatile uint32_t*)(GPIOA_Base + 0x00))
#define GPIOA_IDR  		 (*(volatile uint32_t*)(GPIOA_Base + 0x10))

void delay(void)
{
	for(volatile uint32_t i=0;i<100000;i++);
}


void gpio_init(void)
{
	RCC_AHBENR |= (1<<17)|(1<<21);

	GPIOA_MODER &= ~(3 << (0*2)); // PA0 input mode

	GPIOE_MODER &= ~(3 << (8*2)); //PE8 clearing bits
	GPIOE_MODER |=  (1 << (8*2)); // output mode
}

int main(void)
{

gpio_init();

while(1)
{
	if(GPIOA_IDR & (1 << 0))
	{
		GPIOE_ODR |= (1 << 8);
	}
	else
	{
		GPIOE_ODR &= ~(1 << 8);
	}
}

}

