/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_Base        0x40021000
#define RCC_AHBENR      (*(volatile uint32_t*)(RCC_Base + 0x14))

#define GPIOA_Base      0x48000000
#define GPIOA_MODER     (*(volatile uint32_t*)(GPIOA_Base + 0x00))
#define GPIOA_IDR       (*(volatile uint32_t*)(GPIOA_Base + 0x10))
#define GPIOA_ODR       (*(volatile uint32_t*)(GPIOA_Base + 0x14))

#define PORTA           17   // GPIOA enable bit

void delay(void)
{
    for(uint32_t loop = 0; loop < 100000; loop++);
}

void long_delay(void)
{
    for(uint32_t loop = 0; loop < 1500000; loop++);
}

int main(void)
{
    /* Enable GPIOA clock */
    RCC_AHBENR |= (1 << PORTA);

    /* PA0 as INPUT (USER button) */
    GPIOA_MODER &= ~(3 << (0 * 2));

    /* PA1 to PA10 as OUTPUT */
    for(int i = 1; i <= 10; i++)
    {
        GPIOA_MODER &= ~(3 << (i * 2));
        GPIOA_MODER |=  (1 << (i * 2));
    }

    GPIOA_ODR = 0;

    while(1)
    {
        /* Check USER button (PA0) */
        if (GPIOA_IDR & (1 << 0))
        {
            /* Blink All */
            GPIOA_ODR |= 0x7FE;//0x3FE;
            long_delay();
            GPIOA_ODR &= ~0x7FE;//0x3FE;
            long_delay();

            /* Running light */
            for(int i = 1; i <= 10; i++)
            {
                GPIOA_ODR = (1 << i);
                delay();
            }

            /* Reverse running */
            for(int i = 10; i >= 1; i--)
            {
                GPIOA_ODR = (1 << i);
                delay();
            }

            /* Alternate blinking */
            GPIOA_ODR = 0xAAA;//0x2AA;
            long_delay();
            GPIOA_ODR = 0x554;//0x154;
            long_delay();
        }
        else
        {
        GPIOA_ODR = 0;
        }

    }
}
