/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* stm32f303_i2c1_lcd.c
   Bare-metal STM32F303 Discovery
   I2C1 (PB6=SCL, PB7=SDA) -> PCF8574(0x27) -> 16x2 LCD
*/

#include <stdint.h>

#define RCC_Base		0x40021000
#define RCC_AHBENR		(*(volatile uint32_t*)(RCC_Base + 0x14))

#define GPIOC_Base		0x48000800
#define GPIOC_MODER		(*(volatile uint32_t*)(GPIOC_Base + 0x00))
#define GPIOC_ODR		(*(volatile uint32_t*)(GPIOC_Base + 0x14))

#define GPIOD_Base		0x48000c00
#define GPIOD_MODER		(*(volatile uint32_t*)(GPIOD_Base + 0x00))
#define GPIOD_ODR		(*(volatile uint32_t*)(GPIOD_Base + 0x14))

#define PORTC_EN	19
#define PORTD_EN	20

#define LCD_RS		0
#define LCD_RW		1
#define LCD_EN		2

#define LCD_D0		8
#define LCD_D1		9
#define LCD_D2		10
#define LCD_D3		11
#define LCD_D4		12
#define LCD_D5		13
#define LCD_D6		14
#define LCD_D7		15


void delay_ms(uint16_t i)
{
	while(i)
	{
		for(volatile uint16_t k=0; k<10000; k++);
		i--;
	}
}

void gpio_init(void)
{
	RCC_AHBENR |= (1<<PORTC_EN)|(1<<PORTD_EN);
	GPIOC_MODER &= ~((3<<LCD_RS*2)|(3<<LCD_RW*2)|(3<<LCD_EN*2));
	GPIOC_MODER |=  ((1<<LCD_RS*2)|(1<<LCD_RW*2)|(1<<LCD_EN*2));

	GPIOD_MODER &= ~(0xFFFF<<16);
	GPIOD_MODER |=  (0x5555<<16);

	GPIOC_ODR &= ~((1<<LCD_RS)|(1<<LCD_RW)|(1<<LCD_EN));

}

void LCD_Pulse(void)
{
	GPIOC_ODR |= (1<< LCD_EN);
	delay_ms(2);

	GPIOC_ODR &= ~(1<< LCD_EN);
		delay_ms(2);
}

void LCD_Command(char cmd)
{
	GPIOC_ODR &= ~(1<<LCD_RS);
	GPIOC_ODR &= ~(1<<LCD_RW);
	GPIOD_ODR = (GPIOD_ODR & 0x00FF)|(cmd<<8);
	LCD_Pulse();
}

void LCD_data(char data)
{
	GPIOC_ODR |=  (1<<LCD_RS);
	GPIOC_ODR &= ~(1<<LCD_RW);
	GPIOD_ODR = (GPIOD_ODR & 0x00FF)|(data<<8);
	LCD_Pulse();
}

void LCD_init(void)
{
	delay_ms(20);
	LCD_Command(0x01);
	delay_ms(50);
	LCD_Command(0x38);
	delay_ms(50);
	LCD_Command(0x0C);
	delay_ms(50);
	LCD_Command(0x06);
	delay_ms(50);
	LCD_Command(0x01);
	delay_ms(50);

}

void LCD_string(char *str)
{
	while(*str)
	{
		LCD_data(*str++);
	}
}

int main(void)
{

	gpio_init();
	LCD_init();

	LCD_Command(0x80);
	LCD_data ('H');
	LCD_data ('E');
	LCD_data ('L');
	LCD_data ('L');
	LCD_data ('O');
	LCD_data ('!');
	delay_ms(10);
	LCD_Command(0xC4);
	LCD_string("ALL...");
	delay_ms(50);
	LCD_Command(0x01);
	LCD_Command(0x80);
	LCD_string("WELCOME TO");
	delay_ms(50);
	LCD_Command(0xC0);
	LCD_string("SELAHINDIA..!");
	delay_ms(50);
	LCD_Command(0x01);
	delay_ms(10);
	LCD_Command(0x84);
	LCD_string("DO FOLLOW");
	delay_ms(50);
	LCD_Command(0x01);
	delay_ms(10);
	LCD_Command(0x85);
	LCD_string("OUR");
	delay_ms(50);
	LCD_Command(0x01);
	LCD_Command(0x80);
	LCD_string("YOUTUBE CHANNEL");
	delay_ms(50);
	LCD_Command(0xC0);
	LCD_string("AND INSTAGRAM");
	delay_ms(50);
	LCD_Command(0x01);
	LCD_Command(0x80);
	LCD_string("LIKE SHARE AND");
	delay_ms(50);
	LCD_Command(0xC0);
	LCD_string("SUBSCRIBE..!");
	delay_ms(50);
	LCD_Command(0x01);


	while(1)
		{

		}


}

