/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>

/* ================== RCC ================== */
#define RCC_Base        0x40021000
#define RCC_AHBENR      (*(volatile uint32_t*)(RCC_Base + 0x14))
#define RCC_APB1ENR     (*(volatile uint32_t*)(RCC_Base + 0x1C))

/* ================== GPIO ================== */
#define GPIOA_Base      0x48000000
#define GPIOA_MODER     (*(volatile uint32_t*)(GPIOA_Base + 0x00))
#define GPIOA_PUPDR     (*(volatile uint32_t*)(GPIOA_Base + 0x0C))
#define GPIOA_ODR       (*(volatile uint32_t*)(GPIOA_Base + 0x14))
#define GPIOA_IDR       (*(volatile uint32_t*)(GPIOA_Base + 0x10))

#define GPIOC_Base      0x48000800
#define GPIOC_MODER     (*(volatile uint32_t*)(GPIOC_Base + 0x00))
#define GPIOC_AFRH      (*(volatile uint32_t*)(GPIOC_Base + 0x24))
#define GPIOC_ODR       (*(volatile uint32_t*)(GPIOC_Base + 0x14))

#define GPIOD_Base      0x48000C00
#define GPIOD_MODER     (*(volatile uint32_t*)(GPIOD_Base + 0x00))
#define GPIOD_ODR       (*(volatile uint32_t*)(GPIOD_Base + 0x14))

/* ================== TIM3 ================== */
#define TIM3_BASE       0x40000400
#define TIM3_CR1        (*(volatile uint32_t*)(TIM3_BASE + 0x00))
#define TIM3_CCMR2      (*(volatile uint32_t*)(TIM3_BASE + 0x1C))
#define TIM3_CCER       (*(volatile uint32_t*)(TIM3_BASE + 0x20))
#define TIM3_EGR        (*(volatile uint32_t*)(TIM3_BASE + 0x14))
#define TIM3_PSC        (*(volatile uint32_t*)(TIM3_BASE + 0x28))
#define TIM3_ARR        (*(volatile uint32_t*)(TIM3_BASE + 0x2C))
#define TIM3_CCR3       (*(volatile uint32_t*)(TIM3_BASE + 0x3C))

/* ================== Pin Definitions ================== */
#define PORTA_EN    17
#define PORTC_EN    19
#define PORTD_EN    20
#define TIM3EN      1

#define ir_sens     11
#define buzz        12   // PA12 for buzzer

#define LCD_RS      0
#define LCD_RW      1
#define LCD_EN      2

#define LCD_D0      8
#define LCD_D1      9
#define LCD_D2      10
#define LCD_D3      11
#define LCD_D4      12
#define LCD_D5      13
#define LCD_D6      14
#define LCD_D7      15

#define MAX_TRIES   3

/* ================== Delay ================== */
void delay_ms(uint32_t t){
    while(t--)
        for(volatile uint32_t i=0;i<5000;i++);
}

/* ================== Servo ================== */
void servo_init(void){
    RCC_AHBENR |= (1<<PORTC_EN);
    RCC_APB1ENR |= (1<<TIM3EN);

    GPIOC_MODER &= ~(3<<(8*2));
    GPIOC_MODER |= (2<<(8*2));  // AF mode
    GPIOC_AFRH &= ~(0xF<<0);
    GPIOC_AFRH |= (2<<0);       // AF2 TIM3

    TIM3_PSC = 7;
    TIM3_ARR = 20000-1;

    TIM3_CCMR2 &= ~(0xFF);
    TIM3_CCMR2 |= (6<<4); // PWM mode 1
    TIM3_CCMR2 |= (1<<3);

    TIM3_CCER |= (1<<8);
    TIM3_CCR3 = 1000;     // lock position

    TIM3_EGR = 1;
    TIM3_CR1 |= 1;        // start
}

/* ================== Keypad ================== */
char keypad[4][4] = {
    {'1','2','3','A'},
    {'4','5','6','B'},
    {'7','8','9','C'},
    {'*','0','#','D'}
};

void keypad_init(void){
    RCC_AHBENR |= (1<<PORTA_EN);
    for(int i=0;i<4;i++){        // rows PA0-PA3 input pull-up
        GPIOA_MODER &= ~(3<<(i*2));
        GPIOA_PUPDR &= ~(3<<(i*2));
        GPIOA_PUPDR |= (1<<(i*2));
    }
    for(int i=4;i<8;i++){        // columns PA4-PA7 output
        GPIOA_MODER &= ~(3<<(i*2));
        GPIOA_MODER |= (1<<(i*2));
    }
    GPIOA_ODR |= (0xF<<4);
}

char keypad_scan(void){
    for(int col=0; col<4; col++){
        GPIOA_ODR |= (0xF<<4);
        GPIOA_ODR &= ~(1<<(col+4));
        delay_ms(1);
        for(int row=0;row<4;row++){
            if(!(GPIOA_IDR & (1<<row))){
                delay_ms(20);
                while(!(GPIOA_IDR & (1<<row)));
                return keypad[row][col];
            }
        }
    }
    return 0;
}

/* ================== LCD ================== */
void LCD_pulse(void){
    GPIOC_ODR |= (1<<LCD_EN);
    delay_ms(2);
    GPIOC_ODR &= ~(1<<LCD_EN);
    delay_ms(2);
}
void LCD_Command(char cmd){
    GPIOC_ODR &= ~(1<<LCD_RS);
    GPIOC_ODR &= ~(1<<LCD_RW);
    GPIOD_ODR = (GPIOD_ODR & 0x00FF) | (cmd<<8);
    LCD_pulse();
}
void LCD_data(char data){
    GPIOC_ODR |= (1<<LCD_RS);
    GPIOC_ODR &= ~(1<<LCD_RW);
    GPIOD_ODR = (GPIOD_ODR & 0x00FF) | (data<<8);
    LCD_pulse();
}
void LCD_string(char *str)
{
    while(*str)
    	LCD_data(*str++);
}
void LCD_init(void){
    delay_ms(50);
    LCD_Command(0x38);
    delay_ms(5);
    LCD_Command(0x0C);
    delay_ms(5);
    LCD_Command(0x06);
    delay_ms(5);
    LCD_Command(0x01);
}

/* ================== GPIO Init ================== */
void gpio_init(void){
    RCC_AHBENR |= (1<<PORTA_EN)|(1<<PORTC_EN)|(1<<PORTD_EN);

    // LCD pins
    GPIOC_MODER &= ~((3<<LCD_RS*2)|(3<<LCD_RW*2)|(3<<LCD_EN*2));
    GPIOC_MODER |= ((1<<LCD_RS*2)|(1<<LCD_RW*2)|(1<<LCD_EN*2));

    // Buzzer PA12
    GPIOA_MODER &= ~(3<<(buzz*2));
    GPIOA_MODER |= (1<<(buzz*2));

    // IR PA11 input
    GPIOA_MODER &= ~(3<<(ir_sens*2));

    // LCD Data PD8-PD15
    for(int i=8;i<=15;i++){
        GPIOD_MODER &= ~(3<<(i*2));
        GPIOD_MODER |= (1<<(i*2));
    }
}

/* ================== Main ================== */
int main(void){
    gpio_init();
    LCD_init();
    servo_init();
    keypad_init();

    char password[] = "1234";
    char key_input[5];
    int key_index = 0, wrong_attempts = 0;

    while(1){
        // default display
        LCD_Command(0x01);
        LCD_Command(0x80);
        LCD_string("SWEET HOME");
        delay_ms(500);

        // IR detected
        if(GPIOA_IDR & (1<<ir_sens)){
            LCD_Command(0x01);
            LCD_Command(0x80);
            LCD_string("WELCOME");
            delay_ms(500);
            LCD_Command(0x01);
            LCD_Command(0x80);
            LCD_string("ENTER PASSWORD");

            key_index = 0;
            for(int i=0;i<5;i++) key_input[i]=0;

            // read 4 keys
            while(key_index<4){
                char key = keypad_scan();
                if(key){
                    key_input[key_index++] = key;
                    key_input[key_index] = '\0';

                    GPIOA_ODR |= (1<<buzz);  // short beep
                    delay_ms(100);
                    GPIOA_ODR &= ~(1<<buzz);

                    LCD_Command(0xC0);
                    LCD_string(key_input);
                }
            }

            // check password
            int correct = 1;
            for(int i=0;i<4;i++){
                if(key_input[i]!=password[i]) { correct=0; break; }
            }

            if(correct){
                GPIOA_ODR |= (1<<buzz); // long beep
                TIM3_CCR3 = 2000;       // unlock
                LCD_Command(0x01);
                LCD_Command(0x80);
                LCD_string("ACCESS GRANTED");
                delay_ms(2000);
                GPIOA_ODR &= ~(1<<buzz);
                TIM3_CCR3 = 1000;       // lock
                wrong_attempts=0;
            }else{
                wrong_attempts++;
                GPIOA_ODR |= (1<<buzz);
                delay_ms(300);
                GPIOA_ODR &= ~(1<<buzz);
                LCD_Command(0x01);
                LCD_Command(0x80);
                LCD_string("WRONG PASSWORD");
                delay_ms(1000);

                if(wrong_attempts>=MAX_TRIES){
                    LCD_Command(0x01);
                    LCD_Command(0x80);
                    LCD_string("SYSTEM LOCKED");
                    while(1){
                        GPIOA_ODR |= (1<<buzz);
                        delay_ms(500);
                        GPIOA_ODR &= ~(1<<buzz);
                        delay_ms(500);
                    }
                }
            }
        }
    }
}







