/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>

/* ================= RCC ================= */
#define RCC_BASE        0x40021000
#define RCC_AHBENR      (*(volatile uint32_t*)(RCC_BASE + 0x14))
#define RCC_APB1ENR     (*(volatile uint32_t*)(RCC_BASE + 0x1C))

#define PORTC_EN 19
#define TIM3EN   1

/* ================= GPIOC ================= */
#define GPIOC_BASE 0x48000800
#define GPIOC_MODER (*(volatile uint32_t*)(GPIOC_BASE + 0x00))
#define GPIOC_AFRH  (*(volatile uint32_t*)(GPIOC_BASE + 0x24))

/* ================= TIM3 ================= */
#define TIM3_BASE 0x40000400
#define TIM3_CR1  (*(volatile uint32_t*)(TIM3_BASE + 0x00))
#define TIM3_CCMR2 (*(volatile uint32_t*)(TIM3_BASE + 0x1C))
#define TIM3_CCER (*(volatile uint32_t*)(TIM3_BASE + 0x20))
#define TIM3_EGR  (*(volatile uint32_t*)(TIM3_BASE + 0x14))
#define TIM3_PSC  (*(volatile uint32_t*)(TIM3_BASE + 0x28))
#define TIM3_ARR  (*(volatile uint32_t*)(TIM3_BASE + 0x2C))
#define TIM3_CCR3 (*(volatile uint32_t*)(TIM3_BASE + 0x3C))

/* ================= DELAY ================= */
void delay(volatile uint32_t t)
{
    while(t--);
}

/* ================= INIT ================= */
void servo_init(void)
{
    /* Enable clocks */
    RCC_AHBENR |= (1 << PORTC_EN);
    RCC_APB1ENR |= (1 << TIM3EN);

    /* PC8 → Alternate Function */
    GPIOC_MODER &= ~(3 << (8 * 2));
    GPIOC_MODER |=  (2 << (8 * 2));   // AF mode

    GPIOC_AFRH &= ~(0xF << ((8 - 8) * 4));
    GPIOC_AFRH |=  (2 << ((8 - 8) * 4)); // AF2 (TIM3)

    /* Timer config */
    TIM3_PSC = 7;          // 8 MHz / 8 = 1 MHz
    TIM3_ARR = 20000 - 1;  // 20 ms period (50 Hz)

    /* PWM mode 1 CH3 */
    TIM3_CCMR2 &= ~(0xFF);
    TIM3_CCMR2 |= (6 << 4); // PWM mode 1
    TIM3_CCMR2 |= (1 << 3); // preload

    TIM3_CCER |= (1 << 8);  // enable CH3

    TIM3_CCR3 = 1500;       // center position

    TIM3_EGR = 1;
    TIM3_CR1 |= 1;          // start timer
}

/* ================= MAIN ================= */
int main(void)
{
    servo_init();

    while (1)
    {
        /* 0 degree */
        TIM3_CCR3 = 1000;
        delay(3000000);

        /* 90 degree */
        TIM3_CCR3 = 1500;
        delay(3000000);

        /* 180 degree */
        TIM3_CCR3 = 2000;
        delay(3000000);
    }
}
