/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_Base		0x40021000
#define RCC_AHBENR		(*(volatile uint32_t*)(RCC_Base + 0x14))
#define RCC_APB1ENR		(*(volatile uint32_t*)(RCC_Base + 0x1C))

#define GPIOA_Base		0x48000000
#define GPIOA_MODER		(*(volatile uint32_t*)(GPIOA_Base + 0x00))
#define GPIOA_ODR		(*(volatile uint32_t*)(GPIOA_Base + 0x14))

#define GPIOB_Base		0x48000400
#define GPIOB_MODER		(*(volatile uint32_t*)(GPIOB_Base + 0x00))
#define GPIOB_ODR		(*(volatile uint32_t*)(GPIOB_Base + 0x14))

#define TIM6_Base		0x40001000
#define TIM6_CR1		(*(volatile uint32_t*)(TIM6_Base + 0x00))
#define TIM6_SR 		(*(volatile uint32_t*)(TIM6_Base + 0x10))
#define TIM6_EGR 		(*(volatile uint32_t*)(TIM6_Base + 0x14))
#define TIM6_PSC 		(*(volatile uint32_t*)(TIM6_Base + 0x28))
#define TIM6_ARR 		(*(volatile uint32_t*)(TIM6_Base + 0x2C))

#define EXTI_Base		0x40010400
#define EXTI_IMR		(*(volatile uint32_t*)(EXTI_Base + 0x00))
#define EXTI_RTSR1		(*(volatile uint32_t*)(EXTI_Base + 0x08))
#define EXTI_FTSR1		(*(volatile uint32_t*)(EXTI_Base + 0x0C))
#define EXTI_PR1		(*(volatile uint32_t*)(EXTI_Base + 0x14))

#define NVIC_Base		0xe000e100
#define NVIC_ISER0		(*(volatile uint32_t*)(NVIC_Base + 0x00))
//#define NVIC_ISER1		(*(volatile uint32_t*)(NVIC_Base + 0x04))
//#define NVIC_ISER2		(*(volatile uint32_t*)(NVIC_Base + 0x08))

#define	PORTA_EN	17
#define	PORTB_EN	18

#define	Switch	0
#define	LED		1
#define	LED1	2

#define TIM6EN 4
#define TIM6CEN 0

void TIM6Delay(void)
{
	TIM6_PSC = 7999;
	TIM6_ARR = 999*3;
	TIM6_EGR = 1;
	TIM6_SR = 0;
	TIM6_CR1 |= (1<<TIM6CEN);

	while(!(TIM6_SR & 1));

	TIM6_SR = 0;
	TIM6_CR1 &= ~(1<<TIM6CEN);

}

void init(void)
{
	RCC_AHBENR |= (1 << PORTA_EN) | (1 << PORTB_EN);
	RCC_APB1ENR |= (1 << TIM6EN);

	GPIOA_MODER &= ~(3 << (Switch*2));

	GPIOB_MODER &= ~(3 << (LED*2)|(3 << (LED1*2)));
	GPIOB_MODER |=  (1 << (LED*2)|(1 << (LED1*2)));

	EXTI_IMR |= (1 << Switch);//Enables interrupt for PA0
	EXTI_RTSR1 |= (1 << Switch);//interrupt triggers when:	LOW → HIGH (button press)


	NVIC_ISER0 |= (1 << 6);// EXTI0,Enables interrupt in CPU 	Bit 6 → EXTI0

}

void EXTI0_IRQHandler(void)
{
	EXTI_PR1 |= (1 << Switch);//Clears interrupt flag, Writing 1 clears the flag

	GPIOB_ODR |= (1 << LED);
	TIM6Delay();
	GPIOB_ODR &= ~(1 << LED);

}

int main(void)
{
init();
while(1)
{
GPIOB_ODR |= (1 << LED1);
}
return 0;
}
