/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// A buzzer is connected PE3 and write program generate buzzer sound with a frequency of 1KHZ.

#include<stdint.h>

#define RCC_Base		0x40021000
#define RCC_AHBENR		(*(volatile uint32_t*)(RCC_Base + 0x14))
#define RCC_APB1ENR		(*(volatile uint32_t*)(RCC_Base + 0x1C))

#define GPIOE_Base		0x48001000
#define GPIOE_MODER		(*(volatile uint32_t*)(GPIOE_Base + 0x00))
#define GPIOE_ODR		(*(volatile uint32_t*)(GPIOE_Base + 0x14))

#define TIM6_Base		0x40001000
#define TIM6_CR1		(*(volatile uint32_t*)(TIM6_Base + 0x00))
#define TIM6_SR 		(*(volatile uint32_t*)(TIM6_Base + 0x10))
#define TIM6_EGR 		(*(volatile uint32_t*)(TIM6_Base + 0x14))
#define TIM6_PSC 		(*(volatile uint32_t*)(TIM6_Base + 0x28))
#define TIM6_ARR 		(*(volatile uint32_t*)(TIM6_Base + 0x2C))
//#define TIM6_CR2		(*(volatile uint32_t*)(TIM6_Base + 0x04))
//#define TIM6_DIER		(*(volatile uint32_t*)(TIM6_Base + 0x1C))
//#define TIM6_CNT 		(*(volatile uint32_t*)(TIM6_Base + 0x24))

//#define TIM6_CCR1		(*(volatile uint32_t*)(TIM6_Base + 0x34))
//#define TIM6_CCR2		(*(volatile uint32_t*)(TIM6_Base + 0x38))
//#define TIM6_CCR3		(*(volatile uint32_t*)(TIM6_Base + 0x3C))
//#define TIM6_CCR4		(*(volatile uint32_t*)(TIM6_Base + 0x40))
//#define TIM6_CCMR1	(*(volatile uint32_t*)(TIM6_Base + 0x18))
//#define TIM6_CCER		(*(volatile uint32_t*)(TIM6_Base + 0x20))

#define TIM6EN 4
#define PORTE 21
#define TIM6CEN 0
//#define IOPEEN 22


void TIM6Delay_us(uint32_t us)
{
	TIM6_PSC = 7;
	TIM6_ARR = us - 1;
	TIM6_EGR = 1;
	TIM6_SR = 0;
	TIM6_CR1 |= (1<<TIM6CEN);

	while(!(TIM6_SR & 1));

	TIM6_SR = 0;
	TIM6_CR1 &= ~(1<<TIM6CEN);

}

int main()
{
	RCC_AHBENR |= (1<<PORTE);
	RCC_APB1ENR |= (1 << TIM6EN);

	GPIOE_MODER &= ~(3<<(3*2));
	GPIOE_MODER |=  (1<<(3*2));



while(1)
{
    GPIOE_ODR |= (1<<3);    // HIGH
    TIM6Delay_us(500);      // ON time (25% duty cycle → less loud)

    GPIOE_ODR &= ~(1<<3);   // LOW
    TIM6Delay_us(500);      // OFF time (remaining period)



}
return 0;
}
