/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_Base		0x40021000
#define RCC_AHBENR		(*(volatile uint32_t*)(RCC_Base + 0x14))

//------For Gpio's----------//
#define GPIOA_Base		0x48000000
#define GPIOA_MODER		(*(volatile uint32_t*)(GPIOA_Base + 0x00))
#define GPIOA_IDR		(*(volatile uint32_t*)(GPIOA_Base + 0x10))
#define GPIOA_ODR		(*(volatile uint32_t*)(GPIOA_Base + 0x14))
#define GPIOA_PUPDR		(*(volatile uint32_t*)(GPIOA_Base + 0x0C))

//-------for LCD RS,RW,EN--------//
#define GPIOC_Base		0x48000800
#define GPIOC_MODER		(*(volatile uint32_t*)(GPIOC_Base + 0x00))
#define GPIOC_ODR		(*(volatile uint32_t*)(GPIOC_Base + 0x14))

//--------For LCD DATA PINS--------//
#define GPIOD_BASE      0x48000C00
#define GPIOD_MODER     (*(volatile uint32_t*)(GPIOD_BASE + 0x00))
#define GPIOD_ODR       (*(volatile uint32_t*)(GPIOD_BASE + 0x14))

#define toggle			0 //Automatic mode or manual mode
#define switch			1 //Manual mode start/stop
#define relay			2 //For motor
#define dry_run			3 //Dry_run_sensor

#define low_led			4 //Empty_Tank
#define mid_led			5 //Half_Tank
#define high_led		6 //Full_Tank

#define onled			7 //Manual on indication
#define offled			8 //Manual off indication

#define float_switch1	9 //Low -> Mid
#define float_switch2	10 //Mid - > High

#define PORTA_EN		17
#define PORTC_EN		19
#define PORTD_EN		20

#define LCD_RS			0
#define LCD_RW			1
#define LCD_EN			2

void delay(uint32_t t)
{
	while(t--)
		for(volatile uint32_t i = 0; i < 5000; i++);
}

void gpio_lcd_init(void)
{
	RCC_AHBENR |=  ((1 << PORTC_EN) | (1 << PORTD_EN));
	GPIOC_MODER &= ~((3 << LCD_RS*2) | (3 << LCD_RW*2) | (3 << LCD_EN*2));
	GPIOC_MODER |=  ((1 << LCD_RS*2) | (1 << LCD_RW*2) | (1 << LCD_EN*2));

	for(int i=8;i<=15;i++) {
	    GPIOD_MODER &= ~(3 << (i*2)); // clear
	    GPIOD_MODER |=  (1 << (i*2)); // set as output
	}


	GPIOD_ODR |= ((1 << LCD_RS) | (1 << LCD_RW) | (1 << LCD_EN));

}
void LCD_pulse(void)
{
	GPIOC_ODR |= (1 << LCD_EN);
	delay(2);

	GPIOC_ODR &= ~(1 << LCD_EN);
	delay(2);
}

void LCD_Command(char cmd)
{
	GPIOC_ODR &= ~(1 << LCD_RS);
	GPIOC_ODR &= ~(1 << LCD_RW);
	GPIOD_ODR = (GPIOD_ODR & 0x00FF)| (cmd << 8);
	LCD_pulse();
}

void LCD_data(char data)
{
	GPIOC_ODR |=  (1 << LCD_RS);
	GPIOC_ODR &= ~(1 << LCD_RW);
	GPIOD_ODR  =  (GPIOD_ODR & 0x00FF) | (data << 8);
	LCD_pulse();
}

void LCD_string(char *str)
{
	while(*str){
		LCD_data(*str++);
	}
}

void LCD_init(void)
{
	delay(50);
	LCD_Command(0x01);
	delay(50);
	LCD_Command(0x38);
	delay(50);
	LCD_Command(0x0C);
	delay(50);
	LCD_Command(0x06);
	delay(50);
	LCD_Command(0x01);
	delay(10);
}

void gpio_init(void)
{
	RCC_AHBENR |= (1 << PORTA_EN);

	GPIOA_MODER &= ~((0xFFFF << 0) | (0xFF << 8));
	GPIOA_MODER |=  ((1 << (relay*2)) 	| (1 << (low_led*2))| (1 << (mid_led*2))|
					(1 << (high_led*2)) | (1 << (onled*2)) 	| (1 << (offled*2)));


}

int main(void)
{

	gpio_init();
	gpio_lcd_init();
	LCD_init();

	delay(2);
	LCD_Command(0x80);
	LCD_string("WELCOME");
	delay(500);
	LCD_Command(0x80);
	LCD_string("Water_Tank");
	LCD_Command(0xC0);
	LCD_string("Controller");
	delay(500);
	LCD_Command(0x01);
	delay(50);
while(1)
{
    // RESET LEDs first
    GPIOA_ODR &= ~((1 << low_led) | (1 << mid_led) | (1 << high_led));

	if(GPIOA_IDR & (1 << toggle)) //toggle on -> automatic mode
	{
		if((GPIOA_IDR & (1 << float_switch1)) && (GPIOA_IDR & (1 << float_switch2)))
		{
			//If Both Switchs are 0 the tank is empty

			GPIOA_ODR |= (1 << relay);//Turn on Relay Motor
			GPIOA_ODR |= (1 << low_led);//Turn on Low level indicator light
			delay(500);
			LCD_Command(0x01);
			LCD_Command(0x80);
			LCD_string("Motor ON:");
			LCD_Command(0xC0);
			LCD_string("Low Level");
			delay(1000);

			if(!(GPIOA_IDR & (1 << dry_run)))
			{
				GPIOA_ODR &= ~(1 << relay); //Turn off Relay Motor
				GPIOA_ODR &= ~(1 << low_led);//Turn off low level indicator light
				delay(500);
				LCD_Command(0x01);
				LCD_Command(0x80);
				LCD_string("Motor OFF:");
				LCD_Command(0xC0);
				LCD_string("Dry Run");

			}

			else if((GPIOA_IDR & (1 << float_switch1)) || (GPIOA_IDR & (1 << float_switch2)))
			{
				//If one switch is 0 and another is 1 the tank is half filled

				GPIOA_ODR |= (1 << mid_led);
				delay(500);
				LCD_Command(0x01);
				LCD_Command(0x80);
				LCD_string("Motor ON:");
				LCD_Command(0xC0);
				LCD_string("Half Tank");

			}

		}

		else
		{
			//If Both Switchs are 1 the tank is Full
			GPIOA_ODR &= ~(1 << relay); //Turn off Relay Motor
			GPIOA_ODR |= (1 << high_led); // Turn on
			delay(500);
			LCD_Command(0x01);
			LCD_Command(0x80);
			LCD_string("Motor OFF:");
			LCD_Command(0xC0);
			LCD_string("Full Tank");
		}

		delay(500);
		GPIOA_ODR &= ~(1 << low_led);
		GPIOA_ODR &= ~(1 << mid_led);
		GPIOA_ODR &= ~(1 << high_led);

	}
	else
	{
		if(GPIOA_IDR & (1 << switch))
		{
			GPIOA_ODR |= (1 << onled);//Main Green Light on
			GPIOA_ODR |= (1 << relay);
			delay(500);
			LCD_Command(0x01);
			LCD_Command(0x80);
			LCD_string("Manual Mode");
			LCD_Command(0xC0);
			LCD_string("Motor ON");
		}
		else
		{
			GPIOA_ODR &= ~(1 << onled);//Main Green Light off
			GPIOA_ODR |=  (1 << offled);//Main red Light on
			GPIOA_ODR &= ~(1 << relay);
			delay(500);
			LCD_Command(0x01);
			LCD_Command(0x80);
			LCD_string("Manual Mode");
			LCD_Command(0xC0);
			LCD_string("Motor OFF");
		}
	}
}

}

