/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include<stdint.h>

#define RCC_Base		0x40021000
#define RCC_AHBENR		(*(volatile uint32_t*)(RCC_Base + 0x14))

//------for IR SENSOR-------//
#define GPIOA_Base		0x48000000
#define GPIOA_MODER		(*(volatile uint32_t*)(GPIOA_Base + 0x00))
#define GPIOA_ODR		(*(volatile uint32_t*)(GPIOA_Base + 0x14))
#define GPIOA_IDR		(*(volatile uint32_t*)(GPIOA_Base + 0x10))


//-------for LCD RS,RW,EN--------//
#define GPIOC_Base		0x48000800
#define GPIOC_MODER		(*(volatile uint32_t*)(GPIOC_Base + 0x00))
#define GPIOC_ODR		(*(volatile uint32_t*)(GPIOC_Base + 0x14))

//--------For LCD D0-D8)--------//
#define GPIOD_Base		0x48000C00
#define GPIOD_MODER		(*(volatile uint32_t*)(GPIOD_Base + 0x00))
#define GPIOD_ODR		(*(volatile uint32_t*)(GPIOD_Base + 0x14))

#define PORTA_EN	17
#define PORTC_EN	19
#define PORTD_EN	20

#define ir_sens		1
#define buzz		2
#define motor		3

#define LCD_RS		0
#define LCD_RW		1
#define LCD_EN		2

#define LCD_D0		8
#define LCD_D1		9
#define LCD_D2		10
#define LCD_D3		11
#define LCD_D4		12
#define LCD_D5		13
#define LCD_D6		14
#define LCD_D7		15

void delay(uint32_t t)
{
	while(t--)
		for(volatile uint32_t i = 0; i < 5000; i++);
}
void gpio_init(void)
{
	RCC_AHBENR |=  ((1 << PORTA_EN)  | (1 << PORTC_EN) | (1 << PORTD_EN));
	GPIOC_MODER &= ~((3 << LCD_RS*2) | (3 << LCD_RW*2) | (3 << LCD_EN*2));
	GPIOC_MODER |=  ((1 << LCD_RS*2) | (1 << LCD_RW*2) | (1 << LCD_EN*2));

	GPIOA_MODER &= ~(3 << (ir_sens*2));
	GPIOA_MODER |=  (0 << (ir_sens*2));
	GPIOA_MODER &= ~(3 << (buzz*2));
	GPIOA_MODER |=  (1 << (buzz*2));
	GPIOA_MODER &= ~(3 << (motor*2));
	GPIOA_MODER |=  (1 << (motor*2));


	for(int i=8;i<=15;i++) {
	    GPIOD_MODER &= ~(3 << (i*2)); // clear
	    GPIOD_MODER |=  (1 << (i*2)); // set as output
	}


	GPIOD_ODR |= ((1 << LCD_RS) | (1 << LCD_RW) | (1 << LCD_EN));

}
void LCD_pulse(void)
{
	GPIOC_ODR |= (1 << LCD_EN);
	delay(2);

	GPIOC_ODR &= ~(1 << LCD_EN);
	delay(2);
}

void LCD_Command(char cmd)
{
	GPIOC_ODR &= ~(1 << LCD_RS);
	GPIOC_ODR &= ~(1 << LCD_RW);
	GPIOD_ODR = (GPIOD_ODR & 0x00FF)| (cmd << 8);
	LCD_pulse();
}

void LCD_data(char data)
{
	GPIOC_ODR |=  (1 << LCD_RS);
	GPIOC_ODR &= ~(1 << LCD_RW);
	GPIOD_ODR  =  (GPIOD_ODR & 0x00FF) | (data << 8);
	LCD_pulse();
}

void LCD_string(char *str)
{
	while(*str){
		LCD_data(*str++);
	}
}

void LCD_init(void)
{
	delay(50);
	LCD_Command(0x01);
	delay(50);
	LCD_Command(0x38);
	delay(50);
	LCD_Command(0x0C);
	delay(50);
	LCD_Command(0x06);
	delay(50);
	LCD_Command(0x01);
	delay(10);
}


int main(void)
{
	gpio_init();
	LCD_init();

	delay(10);
	LCD_Command(0x80);
	LCD_string("WELCOME");
	delay(500);
	LCD_Command(0xC0);
	LCD_string("SELAH INDIA");
	delay(500);
	LCD_Command(0x01);
	LCD_Command(0x80);
	LCD_string("IR INITI....!");
	delay(500);
	LCD_Command(0x01);
	delay(10);


	while(1)
	{
		if(GPIOA_IDR & (1 << ir_sens))
			{
			LCD_Command(0x01);
			LCD_Command(0x80);
			LCD_string("NO OBSTACLE");
			LCD_Command(0xC0);
			LCD_string("DETECTED");
			GPIOA_ODR &= ~(1 << buzz);
			GPIOA_ODR |=  (1 << motor);



			}
			else
			{
				LCD_Command(0x01);
				LCD_Command(0x80);
				LCD_string("OBSTACLE DETECTED");
				LCD_Command(0xC0);
				LCD_string("AHEAD");
				GPIOA_ODR |= (1 << buzz);
				GPIOA_ODR &= ~(1 << motor);

				delay(50);

			}
		delay(500);
	}


}

