/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_Base		0x40021000
#define RCC_AHBENR		(*(volatile uint32_t*)(RCC_Base + 0x14))

#define GPIOA_Base		0x48000000
#define GPIOA_MODER		(*(volatile uint32_t*)(GPIOA_Base + 0x00))
#define GPIOA_IDR		(*(volatile uint32_t*)(GPIOA_Base + 0x10))
#define GPIOA_ODR		(*(volatile uint32_t*)(GPIOA_Base + 0x14))

#define PORTA_EN		17
#define switch			0
#define Buzzer			1

void delay()
{
	for(volatile uint32_t i=0;i<1000000;i++);
}

int main()
{
	RCC_AHBENR |= (1 << PORTA_EN);
	GPIOA_MODER &= ~(3<<(switch*2)); //input mode
	GPIOA_MODER &= ~(3<<(Buzzer*2));
	GPIOA_MODER |=  (1<<(Buzzer*2)); //output mode

	while(1)
	{
		if(GPIOA_IDR & (1 << switch))
		{
			GPIOA_ODR |= (1 << Buzzer);
			delay();
			GPIOA_ODR &= ~(1 << Buzzer);

		}
	}
	return 0;
}
