/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//Write a program to implement a running LED pattern on PE8–PE15 that pauses when the user switch (PA0) is pressed and resumes when it is pressed again.


#include <stdint.h>

#define RCC_AHBENR (*(volatile uint32_t*)0x40021014)

#define GPIOE_MODER (*(volatile uint32_t*)0x48001000)
#define GPIOE_ODR   (*(volatile uint32_t*)0x48001014)

#define GPIOA_MODER (*(volatile uint32_t*)0x48000000)
#define GPIOA_IDR   (*(volatile uint32_t*)0x48000010)

void delay()
{
    for(volatile int i = 0; i < 200000; i++);
}

int main()
{
    // Enable clock for PORTA and PORTE
    RCC_AHBENR |= (1 << 17) | (1 << 21);

    // Set PE8–PE15 as output
    GPIOE_MODER &= ~(0xFFFF << 16);
    GPIOE_MODER |=  (0x5555 << 16);

    // Set PA0 as input
    GPIOA_MODER &= ~(3 << 0);

    int pause = 0;
    int led = 8;

    while(1)
    {
        // If button pressed → toggle pause
        if(GPIOA_IDR & (1 << 0))
        {
            pause = !pause;   // change state
            delay();          // simple debounce
        }

        if(pause == 0)   // run LEDs
        {
            GPIOE_ODR = (1 << led);  // turn ON one LED
            delay();

            led++;

            if(led > 15)
                led = 8;
        }
    }
}
