/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE	0x40021000
#define RCC_AHBENR	(*(volatile uint32_t*)(RCC_BASE + 0x14))

#define GPIOD_BASE	0x48000C00
#define GPIOD_MODER	(*(volatile uint32_t*)(GPIOD_BASE + 0x00))
#define GPIOD_ODR	(*(volatile uint32_t*)(GPIOD_BASE + 0x14))

void delay(void)
{
for (uint32_t loop=0;loop<1000000;loop++);
}

int main(void)
{

RCC_AHBENR	|= (1<<20) ;
GPIOD_MODER 	&= ~((3<<(12*2)) | (3<<(13*2)) | (3 << (14*2)) | (3 << (15*2)));
GPIOD_MODER 	|=  ((1<<(12*2)) | (1<<(13*2)) | (1 << (14*2)) | (1 << (15*2)));

//-----------All leds on off method1----------//
while(1)
{

    GPIOD_ODR |=  (1<<12) | (1<<14);
    GPIOD_ODR &= ~((1<<13) | (1<<15));
    delay();


    GPIOD_ODR |=  (1<<13) | (1<<15);
    GPIOD_ODR &= ~((1<<12) | (1<<14));
    delay();
}


return 0;
}
