/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_Base		0x40021000
#define RCC_AHBENR		(*(volatile uint32_t*)(RCC_Base + 0x14))
#define RCC_APB1ENR		(*(volatile uint32_t*)(RCC_Base + 0x1C))

#define GPIOB_Base		0x48000400
#define GPIOB_MODER		(*(volatile uint32_t*)(GPIOB_Base + 0x00))
#define GPIOB_OTYPER	(*(volatile uint32_t*)(GPIOB_Base + 0x04))
#define GPIOB_PUPDR		(*(volatile uint32_t*)(GPIOB_Base + 0x0C))
#define GPIOB_AFRL		(*(volatile uint32_t*)(GPIOB_Base + 0x20))

#define I2C1_Base		0x40005400
#define I2C1_CR1		(*(volatile uint32_t*)(I2C1_Base + 0x00))
#define I2C1_CR2		(*(volatile uint32_t*)(I2C1_Base + 0x04))
#define I2C1_TIMINGR	(*(volatile uint32_t*)(I2C1_Base + 0x10))
#define I2C1_ISR		(*(volatile uint32_t*)(I2C1_Base + 0x18))
#define I2C1_ICR		(*(volatile uint32_t*)(I2C1_Base + 0x1C))
#define I2C1_TXDR		(*(volatile uint32_t*)(I2C1_Base + 0x28))

#define GPIOB_EN		18
#define I2C1_EN			21

#define LCD_ADDR		0x27
#define RS				0x01
#define RW				0x02
#define EN				0x04
#define BL				0x08

#define SCL				6	//PB6
#define SDA				7	//PB7

void delay_ms(uint32_t t)
{
	while(t--)
	{
		for(volatile uint32_t i=0;i<8000;i++);
	}
}


void I2C1_init(void)
{

	RCC_AHBENR |= (1 << GPIOB_EN);
	RCC_APB1ENR |= (1 << I2C1_EN);

	GPIOB_MODER &= ~((3 << (SCL*2)) | (3 << (SDA*2)));
	GPIOB_MODER |=  ((2 << (SCL*2)) | (2 << (SDA*2)));

	GPIOB_OTYPER |= ((1 << SCL) | (1 << SDA));

	GPIOB_PUPDR |= ((1 << SCL) | (1 << SDA));

    GPIOB_AFRL &= ~((0xF << (SCL*4)) | (0xF << (SDA*4)));
    GPIOB_AFRL |=  ((0x4 << (SCL*4)) | (0x4 << (SDA*4)));

	I2C1_CR1 &= ~(1);
	I2C1_TIMINGR = 0x10420F13;
			/*TIMINGR =
			(PRESC << 28) |			= (1 << 28)		PRESC (0x1)
			(SCLDEL << 20) |		| (4 << 20)		SSCLDEL + SDADEL (0x04 0x2)
			(SDADEL << 16) |		| (2 << 16)
			(SCLH << 8)  |			| (15 << 8)		SCLH (0x0F = 15)
			(SCLL)					| 19			SCLL (0x13 = 19)*/

	I2C1_CR1 |= (1);

}

void I2C1_Write(uint8_t addr, uint8_t data)
{
    while(I2C1_ISR & (1 << 15));

    I2C1_CR2 =
        (addr << 1) |   // device address
        (1 << 16) |     // number of bytes = 1
        (1 << 25);      // start condition

    I2C1_CR2 |= (1 << 13); // start transfer

      while(!(I2C1_ISR & (1 << 1)));

      I2C1_TXDR = data;

    while(!(I2C1_ISR & (1 << 5)));

       I2C1_ICR |= (1 << 5);
}


void LCD_pulse(uint8_t data)
{
    I2C1_Write(LCD_ADDR, data | EN); // EN = 1
    delay_ms(2);

    I2C1_Write(LCD_ADDR, data & ~EN); // EN = 0
    delay_ms(2);
}


void LCD_write4(uint8_t nibble, uint8_t rs)
{
    uint8_t data = 0;

    // Convert 4-bit nibble into LCD data pins (D4-D7)
    if(nibble & 0x01) data |= (1 << 4);
    if(nibble & 0x02) data |= (1 << 5);
    if(nibble & 0x04) data |= (1 << 6);
    if(nibble & 0x08) data |= (1 << 7);

    // Set RS = 1 for data, 0 for command
    if(rs) data |= RS;

    // Keep backlight ON
    data |= BL;

    LCD_pulse(data);
}


void LCD_send(uint8_t value, uint8_t rs)
{
    LCD_write4(value >> 4, rs);   // send upper 4 bits
    LCD_write4(value & 0x0F, rs); // send lower 4 bits
}


/* Send command to LCD */
void LCD_cmd(uint8_t cmd)
{
    LCD_send(cmd, 0);
}


/* Send character/data to LCD */
void LCD_data(char data)
{
    LCD_send(data, 1);
}


/* ================= LCD initialization ================= */
void LCD_init(void)
{
    delay_ms(50); // wait for LCD power-up

    // Initialization sequence for 4-bit mode
    LCD_write4(0x03,0);
    delay_ms(5);
    LCD_write4(0x03,0);
    delay_ms(5);
    LCD_write4(0x03,0);
    delay_ms(5);
    LCD_write4(0x02,0);
    delay_ms(5);

    // Configure LCD
    LCD_cmd(0x28);  // 4-bit mode, 2 lines
    LCD_cmd(0x0C);  // display ON, cursor OFF
    LCD_cmd(0x06);  // auto increment cursor
    LCD_cmd(0x01);  // clear display

    delay_ms(5);
}


/* Print string on LCD */
void LCD_string(char *str)
{
    while(*str)
    {
        LCD_data(*str++);
    }
}


int main(void)
{
    // Initialize I2C and LCD
    I2C1_init();
    LCD_init();

    // Print first line
    LCD_cmd(0x80); // move cursor to line 1
    LCD_string("HELLO");

    // Print second line
    LCD_cmd(0xC0); // move cursor to line 2
    LCD_string("I'm RAVITEJA...");

    // Infinite loop
    while(1)
    {
    }
}
