/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//Blink the LEDs on the Discovery board as the connections in the schematic
//led blink program

#include<stdint.h>
#include "ravi.h"

int i;
void delay(){

	for(volatile uint32_t loop=0;loop<1000;loop++);
}

int main(void){

	RCC ->AHBENR |= (1<<PORTE);

	for(i=8;i<16;i++)
	{
		GPIOE -> MODER &= ~(1<<(i*2));
		GPIOE -> MODER |=  (1<<(i*2));
	}

	while(1){

		for(i=8;i<16;i++)
		{
			GPIOE -> ODR &= ~(1<<i);
			delay();
			GPIOE -> ODR |=  (1<<i);
			delay();
		}
	}
	return 0;
}
