/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * Write a code to interface a switch at PA0, an LED at PE13, a relay at PB6, and a buzzer at PB5 such that when the switch is pressed, the LED and relay turn ON, and the buzzer turns ON for 2 seconds only, after which it turns OFF while the LED and relay remain ON.
 */


#include <stdint.h>

#define RCC_Base		0x40021000
#define RCC_AHBENR		(*(volatile uint32_t*)(RCC_Base + 0x14))

#define GPIOE_Base		0x48001000
#define GPIOE_MODER		(*(volatile uint32_t*)(GPIOE_Base + 0x00))
#define GPIOE_ODR		(*(volatile uint32_t*)(GPIOE_Base + 0x14))

#define GPIOA_Base		0x48000000
#define GPIOA_MODER		 (*(volatile uint32_t*)(GPIOA_Base + 0x00))
#define GPIOA_IDR  		 (*(volatile uint32_t*)(GPIOA_Base + 0x10))

#define GPIOB_Base		0x48000400
#define GPIOB_MODER		 (*(volatile uint32_t*)(GPIOB_Base + 0x00))
#define GPIOB_ODR  		 (*(volatile uint32_t*)(GPIOB_Base + 0x14))


void delay(uint32_t k)
{
	while(k)
	{
	for(volatile uint32_t i=0;i<10000;i++);
	k--;
	}
}



void gpio_init(void)
{
	RCC_AHBENR |= (1<<17)|(1<<21)|(1<<18);

	GPIOA_MODER &= ~(3 << (0*2)); // PA0 input mode

	GPIOE_MODER &= ~(3 << (13*2)); //PE13 clearing bits
	GPIOE_MODER |=  (1 << (13*2)); // output mode

	GPIOB_MODER &= ~(3 << (6*2)) | (3 << (5*2)); // clearing Buzzer bits
	GPIOB_MODER |=  (1 << (6*2)) | (1 << (5*2)); //output mode
}


int main(void)
{

gpio_init();

while(1)
{
	if(GPIOA_IDR & (1 << 0))
	{
		GPIOE_ODR |= (1 << 13);
		GPIOB_ODR |= (1 << 6) | (1 << 5);
		delay(2000);
		GPIOB_ODR &= ~(1 << 5);
	}
}
}
