/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//Write a code to interface an LED at PE9 and a buzzer at PB5 such that both blink/beep simultaneously with a delay of 500 ms.


#include <stdint.h>

#define RCC_Base		0x40021000
#define RCC_AHBENR		(*(volatile uint32_t*)(RCC_Base + 0x14))

#define GPIOE_Base		0x48001000
#define GPIOE_MODER		(*(volatile uint32_t*)(GPIOE_Base + 0x00))
#define GPIOE_ODR		(*(volatile uint32_t*)(GPIOE_Base + 0x14))

#define GPIOB_Base		0x48000400
#define GPIOB_MODER		 (*(volatile uint32_t*)(GPIOB_Base + 0x00))
#define GPIOB_ODR  		 (*(volatile uint32_t*)(GPIOB_Base + 0x14))

void delay_ms(uint16_t i)
{
	while(i)
	{
		for(volatile uint16_t k=0; k<10000; k++);
		i--;
	}
}
void gpio_init(void)
{
	RCC_AHBENR |= (1<<21)|(1<<18);

	GPIOE_MODER &= ~(3 << (9*2)); //PE9
	GPIOE_MODER |=  (1 << (9*2)); // output mode

	GPIOB_MODER &= ~(3 << (5*2)); // clearing Buzzer bits
	GPIOB_MODER |=  (1 << (5*2)); //output mode
}


int main(void)
{

gpio_init();

while(1)
{
		GPIOE_ODR |= (1 << 9);
		GPIOB_ODR |= (1 << 5);
		delay_ms(500);
		GPIOE_ODR &= ~(1 << 9);
		GPIOB_ODR &= ~(1 << 5);
		delay_ms(500);
		}

}

