/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//Write a program where each press of the user switch toggles the state of all LEDs (PE8–PE15).

#include <stdint.h>

#define RCC_Base		0x40021000
#define RCC_AHBENR		(*(volatile uint32_t*)(RCC_Base + 0x14))

#define GPIOE_Base		0x48001000
#define GPIOE_MODER		(*(volatile uint32_t*)(GPIOE_Base + 0x00))
#define GPIOE_ODR		(*(volatile uint32_t*)(GPIOE_Base + 0x14))

#define GPIOA_Base		0x48000000
#define GPIOA_MODER		(*(volatile uint32_t*)(GPIOA_Base + 0x00))
#define GPIOA_ODR		(*(volatile uint32_t*)(GPIOA_Base + 0x14))
#define GPIOA_IDR		(*(volatile uint32_t*)(GPIOA_Base + 0x10))

#define PORTA_EN		17
#define PORTE_EN		21

#define Switch			0

void delay()
{
    for(volatile int i = 0; i < 50000; i++);
}

int main()
{
    RCC_AHBENR |= (1<<PORTA_EN) | (1<<PORTE_EN);

    GPIOE_MODER &= ~(0xFFFF << 16);
    GPIOE_MODER |=  (0x5555 << 16);

    GPIOA_MODER &= ~(3 << 0);

    int lastButton = 0;

    while(1)
    {
        int currentButton = (GPIOA_IDR & 1);

        if(currentButton == 1 && lastButton == 0)
        {
            GPIOE_ODR ^= 0xFF00;   // toggle LEDs
            delay();              // simple debounce
        }

        lastButton = currentButton;
    }
}






